# Generated by Django 5.1.3 on 2024-11-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=150, unique=True)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Unfinished', 'Unfinished'), ('Postponed', 'Postponed'), ('Cancelled', 'Cancelled')], default='Unfinished', max_length=20)),
            ],
        ),
    ]
