# Generated by Django 5.1.3 on 2024-11-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='sr_no',
            field=models.IntegerField(default=1),
        ),
    ]
