# Generated by Django 5.1.3 on 2024-11-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starttime',
            name='start_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='sr_no',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='task',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
