# Generated by Django 5.1.3 on 2024-11-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_starttime_start_time_alter_todomodel_sr_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='time_required',
            field=models.IntegerField(default=0),
        ),
    ]
